config/routes.rb
Blogee::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "register",
    :edit => "settings"
  }, :controllers => { :registrations => "registrations" }

  # Keep unless we just make a CMS...
  get 'about/',     to: 'pages#about',    as: 'page_about'
  get 'team/',      to: 'pages#team',     as: 'page_team'
  get 'features/',  to: 'pages#features', as: 'page_features'

  get 'explore/', to: 'explore#index', as: 'explore'

  scope :admin do
    get '', to: 'admin#index', as: 'admin'
    get 'users', to: 'admin#users', as: 'admin_user_management'
    get 'articles', to: 'admin#articles', as: 'admin_article_management'
  end

  namespace :api do
    namespace :users, path: 'user' do
      get :follower_count
      post :follow
      post :unfollow
    end
    namespace :articles, path: 'article' do
      post :basic_stats
    end
  end

  # Dashboard is ajax based, SPA... Doesn't need much.
  scope 'dashboard' do
    get '',   to: 'dashboard#index',    as: 'user_dashboard'
  end

  resource :articles,         path: 'article', only: [:new, :edit, :create, :update, :destroy]
  resource :article_sets,     path: 'set'
  resource :article_comments, path: 'comments'

  #### VERY BOTTOM IN ORDER OF IMPORTANCE
  get 'article/:id', to: 'articles#show'
  get ':username', to: 'users#show', as: 'user_profile'
  scope ':username' do
    get ':id/:title', to: 'articles#show', as: 'article_show'
  end

  devise_scope :user do
    authenticated :user do
      root to: 'users#home', as: 'user_home'
    end
    unauthenticated :user do
      root to: 'pages#landing', as: 'page_landing'
    end
  end

  #### NOT IMPORTANT!!!!
  ## Implement later...
  ## New article url structure...
  # scope ':username' do
  #   get ':id', to: 'articles#show', as: 'article'
  # end

end

app/models/article.rb
class Article < ActiveRecord::Base
  # default_scope { order("created_at DESC") }

  scope :recent, -> { order("created_at DESC") }
  scope :today, -> { where("articles.created_at >= ? and articles.created_at <= ?", Date.today.beginning_of_day, Date.today.end_of_day) }
  scope :with_visits, lambda { joins(:visit) }
  scope :trending_with_unique, -> { with_visits.order('visits.unique_visits DESC')}
  scope :trending_with_total, -> { with_visits.order("visits.total_visits DESC") }

  enum status: [:draft, :shared_draft, :published]

  has_attached_file :image, :styles => { :large => "900x900>", :small => "300x300#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  belongs_to :article_set

  has_one :visit, as: :visitable
  has_many :article_comments
  has_many :tags
  
  def similar(count=5)
    Article.all.take(count)
  end

  def more_from_author(count=5)
    articles = Article.where(user: self.user).recent.take(count)
    articles.delete(self)
    articles
  end

  def recommended
    Article.first()
  end

  def can_edit?(user)
    (self.user == user) ? true : false
  end

  def can_delete(user)
    (self.user == user) ? true : false
  end

  def param_title
    self.title.parameterize
  end

  # Add later when we know how to use it...
  # def to_param
  #   self.title.parameterize
  # end

end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  respond_to :json
  before_action :get_article, only: [:basic_stats]

  def basic_stats
    unique_visits = @article.visit.unique_visits rescue 0
    total_visits = @article.visit.total_visits rescue 0

    render :json => {
      info: @article,
      user: @article.user,
      unique_visits: unique_visits,
      total_visits: total_visits
    }
  end

  private

    def get_article
      @article = Article.find(params[:id])
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_article, only: [:update, :edit, :destroy]

  def new
  end

  def edit
  end

  def show
    @article = Article.find(params[:id])
    Visit.track(@article, request)
  end

  def create
    respond_to do |format|

      @article = current_user.articles.create(article_params)
      if @article.save()
        format.html do
          redirect_to article_show_path(@article.user.username, @article, @article.param_title)
        end
        format.json {
          render :json => { status: :created, message: "Successfully created article.", 
            article: @article, 
            location: article_show_path(@article.user.username, @article) }
        }
      else
        format.html do
          render 'new', notice: 'There was an error. Please try again.'
        end
        format.json {
          render :json => { status: :unprocessible_entity, 
            message: "Oops... something went wrong, please try again." }
        }
      end

    end
  end

  def update
    if @article.update_attributes(article_params)
      respond_to do |f|
        f.json { render :json => { status: :ok, message: "Successfully updated article!" } }
      end
    else
      respond_to do |f|
        f.json { render :json => { status: :ok, message: "Oops... Something went wrong, we're working on it." } }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(article_params)
        format.html do
          redirect_to article_show_path(@article.user.username, @article), notice: "Article was updated successfully!"
        end
      else
        format.html do
          render 'edit', notice: 'Oops.. Something went wrong, we are working on it.'
        end
      end
    end
  end

  def destroy
    if @article.can_delete?(current_user)
      @article.destroy
      redirect_to user_home_path, notice: "Deleted this article."
    else
      redirect_to @articled, notice: "You cannot delete this article."
    end
  end

  def get_article
    @article = Article.find(params[:id])
  end

  private

    def article_params
      params.require(:article).permit(:title, :subtitle, :content, :image, :article_set_id, :status)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="row">
  <%= form_for @article do |f| %>

    <%= f.file_field :image %>
    <%=	f.text_field :title, placeholder: "Title" %>
    <%= f.text_field :subtitle, placeholder: "Subtitle" %>
    <%=	f.text_area :content, placeholder: "Write your story here..." %>

    <%=	f.submit "Save Changes", :class => 'button large' %>
    
  <% end %>

  <%= button_to "Delete", article_destroy_path(@article), method: :delete, class: 'button alert' %>
</div>

app/views/articles/new.html.erb
<div id="articleCreator" class="article-creator test-article-creator">

	<div class="content-creation">
		<%= form_for current_user.articles.new do |f| %>
			<%= f.collection_select(:article_set_id, current_user.article_sets, :id, :name) %>
			<%= f.file_field :image, class: "image-upload" %>
			<%=	f.text_field :title, placeholder: "Title", class: "title" %>
			<%= f.text_field :subtitle, placeholder: "Subtitle", class: "subtitle" %>
			<%=	f.hidden_field :content, class: "content-editor-content" %>

			<div id="content-editor" class="content-editor article-main-content"></div>

			<%=	f.submit "Save & Publish", :class => 'button success publish' %>
		<% end %>
	</div>
	
</div>

app/views/articles/show.html.erb
<%= content_for(:title) { @article.title } %>
<% content_for :meta do %>

<meta name="description" content="<%= "#{@article.title} published by #{@article.user.name}." %>" />

<!-- Twitter Card data --> 
<meta name="twitter:card" content="summary_large_image"> 
<meta name="twitter:site" content="@oovrepub"> 
<meta name="twitter:title" content="<%= truncate(@article.title, length: 70) %>"> 
<meta name="twitter:description" content="<%= truncate(strip_tags(@article.content), length: 200) %>"> 
<!-- <meta name="twitter:creator" content="@author_handle">  -->
<!-- Twitter Summary card images must be at least 200x200px --> 
<meta name="twitter:image:src" content="<%= @article.image.url(:small) %>">

<!-- Open Graph data --> 
<meta property="og:title" content="<%= @article.title %>" /> 
<meta property="og:type" content="article" /> 
<meta property="og:url" content="<%= article_show_path(@article.user.username, @article.id, @article.param_title) %>" />
<meta property="og:image" content="<%= @article.image.url(:small) %>" />
<meta property="og:description" content="<%= truncate(strip_tags(@article.content), length: 70) %>" />
<meta property="article:published_time" content="<%= @article.created_at %>" /> 
<meta property="article:modified_time" content="<%= @article.updated_at %>" /> 
<!-- <meta property="article:section" content="Article Section" />  -->
<!-- <meta property="article:tag" content="Article Tag" />  -->
<meta property="og:site_name" content="Oovre" /> 
<!-- <meta property="fb:admins" content="Facebook numeric ID" /> -->

<% end %>

<div class="article-view">

	<% if @article.image.exists? %>
		<div class="background-image"><div class="bg" style="background:url('<%= @article.image.url(:large) %>') no-repeat center center fixed;"></div></div>
	<% end %>

	<div class="container">
		<div class="col-8 av-info">
			<div class="title"><%= @article.title %></div>
			<div class="subtitle"><%= @article.subtitle %></div>
		</div>
		<div class="col-4 info">
			<!-- <div class="social-share">SHARE BUTTONS HERE EVENTUALLY</div> -->
			<div class="time-set">published <%= time_ago_in_words(@article.created_at) %> ago</div>
			<div class="user-info">
				Created by <a href="<%= user_profile_path(@article.user.username) %>"><%= @article.user.name %></a>
			</div>
			<% if @article.can_edit?(current_user) %><a class="ghost primary" id="edit_article_btn">Edit</a><% end %>
		</div>

	</div>

	<div class="container">

		<div class="col-8 push-2 article-main-content">
			<%= sanitize @article.content.html_safe, tags: %w(p div b u i a h1 h2 h3 h4 h5 ul ol li br), attributes: %w(href class id) %>
		</div><!-- 
		<div class="col-8 push-2 actions">
			<hr class="divider">
			<div>
				<div class="donate">
					<p class="like">Like this article?</p>
					<p class="donation">Make a <a href="#">Donation</a> to <%= @article.user.first_name %>.</p>
				</div>
			</div>
		</div> -->

	</div>
</div>

<div class="container">
	<% if !@article.more_from_author(3).empty? %>
	<div class="section-title">More From <%= @article.user.name %></div>
	<div class="user-articles">
		<div class="articles">
			<% @article.more_from_author(3).each do |article| %>
				<%= render 'articles/cards/article1', article: article %>
			<% end %>
		</div>
	</div>
	<% end %>

	<!-- <div class="section-title">More like this</div>
	<div class="user-articles">
		<div class="articles">
			<% @article.similar(3).each do |article| %>
				<%= render 'articles/cards/article1', article: article %>
			<% end %>
		</div>
	</div> -->
</div>