config/routes.rb
Blogee::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "register",
    :edit => "settings"
  }, :controllers => { :registrations => "registrations" }

  # Keep unless we just make a CMS...
  get 'about/',     to: 'pages#about',    as: 'page_about'
  get 'team/',      to: 'pages#team',     as: 'page_team'
  get 'features/',  to: 'pages#features', as: 'page_features'

  get 'explore/', to: 'explore#index', as: 'explore'

  scope :admin do
    get '', to: 'admin#index', as: 'admin'
    get 'users', to: 'admin#users', as: 'admin_user_management'
    get 'articles', to: 'admin#articles', as: 'admin_article_management'
  end

  namespace :api do
    namespace :users, path: 'user' do
      get :follower_count
      post :follow
      post :unfollow
    end
    namespace :articles, path: 'article' do
      post :basic_stats
    end
  end

  # Dashboard is ajax based, SPA... Doesn't need much.
  scope 'dashboard' do
    get '',   to: 'dashboard#index',    as: 'user_dashboard'
  end

  resource :articles,         path: 'article', only: [:new, :edit, :create, :update, :destroy]
  resource :article_sets,     path: 'set'
  resource :article_comments, path: 'comments'

  #### VERY BOTTOM IN ORDER OF IMPORTANCE
  get 'article/:id', to: 'articles#show'
  get ':username', to: 'users#show', as: 'user_profile'
  scope ':username' do
    get ':id/:title', to: 'articles#show', as: 'article_show'
  end

  devise_scope :user do
    authenticated :user do
      root to: 'users#home', as: 'user_home'
    end
    unauthenticated :user do
      root to: 'pages#landing', as: 'page_landing'
    end
  end

  #### NOT IMPORTANT!!!!
  ## Implement later...
  ## New article url structure...
  # scope ':username' do
  #   get ':id', to: 'articles#show', as: 'article'
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  scope :recent, -> {}
  scope :recent, -> { order("created_at DESC") }
  scope :today, -> { where("users.created_at >= ? and users.created_at <= ?", Date.today.beginning_of_day, Date.today.end_of_day) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :cover_image, :styles => { :large => "900x900#" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :cover_image, :content_type => /\Aimage\/.*\Z/

  has_one :visit, as: :visitable
  has_many :articles
  has_many :article_sets
  has_many :article_set_subscriptions
  has_many :article_comments
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship'
  has_many :followers, through: :reverse_relationships

  def following?(other_user_id)
    relationships.find_by(followed_id: other_user_id)
  end

  def follow!(other_user_id)
    relationships.create!(followed_id: other_user_id)
  end

  def unfollow!(other_user_id)
    relationships.find_by(followed_id: other_user_id).destroy
  end

  def recent_articles(count=5)
    self.articles.recent.take(count)
  end

  def article_views_unique_today
    0
  end

  def article_views_total_today
    0
  end

  def gravatar
    id = Digest::MD5.hexdigest(self.email.downcase)
    "http://gravatar.com/avatar/#{id}.png?s=50"
  end

  def name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  respond_to :json

  def follower_count
    user = User.find(params[:user_id])
    if user.present?
      count = user.followers.count
      message = {follower_count: count}
      status = :ok
    else
      message = "couldn't fetch followers for this user."
      status = :unprocessible_entity
    end
    render_json(message, status)
  end

  def follow
    message = current_user.follow!(params[:user_id])
    render_json(message, :ok)
  end

  def unfollow
    message = current_user.unfollow!(params[:user_id])
    render_json(message, :ok)
  end

  def render_json(message=nil, status)
    render :json => { message: message, status: status }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_username(params[:username])
    respond_to do |format|
      format.html { 
        if @user != current_user 
          Visit.track(@user, request) 
        end 
      }   # show.html
      format.json { render json: @user, status: :ok }
    end
  end

  def home
    @articles = Article.recent.take(20)
    if Article.today.trending_with_total.empty?
      @trending = Article.recent.trending_with_unique.take(5)
    else
      @trending = Article.today.trending_with_unique.take(5)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<div class="container">
	
	<div class="sidebar">
		<div class="trending-articles">
			<% @trending.each do |article| %>
				<div class="article-card-1">
					
					<% if article.image.exists? %>
					<div class="article">
						<div class="background-image" style="background:url('<%= article.image.url(:large) %>') no-repeat center center; background-size:cover;"></div>
						<div class="overlay"></div>
					<% else %>
					<div class="article dark">
					<% end %>

						<div class="info">
							<div class="user">
								<a href="<%= user_profile_path(article.user.username) %>">
								<%= image_tag article.user.avatar.url(:thumb), class: 'profile-img' %>
								<span class="name"><%= article.user.name %></span>
								</a>
							</div>
						</div>

						<div class="article-content">
							<a href="<%= article_show_path(article.user.username, article.id, article.param_title) %>"><div class="title"><%= article.title %></div></a>
						</div>

					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="article-stream">
		<% @articles.each do |article| %>
			
			<div class="article-card-1">
				
				<% if article.image.exists? %>
				<div class="article">
					<div class="background-image" style="background:url('<%= article.image.url(:large) %>') no-repeat center center; background-size:cover;"></div>
					<div class="overlay"></div>
				<% else %>
				<div class="article dark">
				<% end %>

					<div class="info">
						<div class="time"><%= time_ago_in_words(article.created_at) %> ago</div>
						
						<div class="user">
							<a href="<%= user_profile_path(article.user.username) %>">
							<%= image_tag article.user.avatar.url(:thumb), class: 'profile-img' %>
							<span class="name"><%= article.user.name %></span>
							</a>
						</div>

					</div>

					<div class="article-content">
						<a href="<%= article_show_path(article.user.username, article.id, article.param_title) %>"><div class="title"><%= article.title %></div></a>
						<% if !article.subtitle.blank? %>
						<div class="subtitle"><%= article.subtitle %></div>
						<% end %>
					</div>

					<a href="<%= article_show_path(article.user.username, article.id, article.param_title) %>">
					<div class="readmore">
						<p>Read More</p>
					</div>
					</a>

				</div>
			</div>

		<% end %>
	</div>

</div>

app/views/users/show.html.erb
<% content_for(:title){ "#{@user.name} | Oovre" } %>

<div id="user-information" data-user-id="<%= @user.id %>" data-user-name="<%= @user.name %>"></div>

<div class="profile-header">
	<div class="cover-container">
		<div class="cover" style="background-image:url(<%= @user.cover_image.url %>);"></div>
		<% if @user.cover_image? %>
			<!-- <%= image_tag @user.cover_image.url, :class => 'cover' %> -->
		<% end %>
		<div class="cover-overlay"></div>
	</div>
	<div class="user">
		<div class="follow">
			<% if user_signed_in? %>
				<% if @user != current_user %>
					<div class="follow-group  <%= if current_user.following?(@user) then "is-following" else "not-following" end %>">
						<button id="following" class="button primary following">Following <%= @user.first_name %></button>
						<button id="unfollow-user" data-user-id="<%= @user.id %>" class="button alert unfollow">Unfollow <%= @user.first_name %></button>
						<button id="follow-user" data-user-id="<%= @user.id %>" class="button success follow">Follow <%= @user.first_name %></button>
					</div>
				<% end %>
			<% end %>
		</div>
		<div class="info">
			<%= image_tag @user.avatar.url(:thumb), :class => 'avatar' %>
			<div class="name"><%= @user.name %></div>
			<div class="bio"><%= @user.bio if !@user.bio.blank? %></div>
		</div>
		<div class="stats">
			<div class="stat">
				<div class="num"><%= @user.articles.count rescue 0 %></div>
				<div class="name"><%= "article".pluralize(@user.articles.count) %></div>
			</div>
		  <div class="stat">
				<div class="num" id="follower-count"><%= @user.followers.count rescue 0 %></div>
				<div class="name"><%= "follower".pluralize(@user.followers.count) %></div>
			</div>
			<div class="stat">
				<div class="num"><%= @user.visit.unique_visits rescue 0 %></div>
				<div class="name">page <%= "view".pluralize(@user.visit.unique_visits) %></div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="user-articles">

		<div class="articles">
			<% @user.recent_articles(20).each do |article| %>
				<%= render 'articles/cards/article1', article: article %>
			<% end %>
		</div>

	</div>
</div>