config/routes.rb
Blogee::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "register",
    :edit => "settings"
  }, :controllers => { :registrations => "registrations" }

  # Keep unless we just make a CMS...
  get 'about/',     to: 'pages#about',    as: 'page_about'
  get 'team/',      to: 'pages#team',     as: 'page_team'
  get 'features/',  to: 'pages#features', as: 'page_features'

  get 'explore/', to: 'explore#index', as: 'explore'

  scope :admin do
    get '', to: 'admin#index', as: 'admin'
    get 'users', to: 'admin#users', as: 'admin_user_management'
    get 'articles', to: 'admin#articles', as: 'admin_article_management'
  end

  namespace :api do
    namespace :users, path: 'user' do
      get :follower_count
      post :follow
      post :unfollow
    end
    namespace :articles, path: 'article' do
      post :basic_stats
    end
  end

  # Dashboard is ajax based, SPA... Doesn't need much.
  scope 'dashboard' do
    get '',   to: 'dashboard#index',    as: 'user_dashboard'
  end

  resource :articles,         path: 'article', only: [:new, :edit, :create, :update, :destroy]
  resource :article_sets,     path: 'set'
  resource :article_comments, path: 'comments'

  #### VERY BOTTOM IN ORDER OF IMPORTANCE
  get 'article/:id', to: 'articles#show'
  get ':username', to: 'users#show', as: 'user_profile'
  scope ':username' do
    get ':id/:title', to: 'articles#show', as: 'article_show'
  end

  devise_scope :user do
    authenticated :user do
      root to: 'users#home', as: 'user_home'
    end
    unauthenticated :user do
      root to: 'pages#landing', as: 'page_landing'
    end
  end

  #### NOT IMPORTANT!!!!
  ## Implement later...
  ## New article url structure...
  # scope ':username' do
  #   get ':id', to: 'articles#show', as: 'article'
  # end

end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<header id="header" class="header">
	<div class="header-container">
		<a href="<%= user_home_path %>"><%= image_tag "oovre-logo.png", class: 'logo' %></a>
		<!-- <div class="navigation"><i class="fa fa-menu"></i></div> -->
		<div class="user">
			<div class="new"><a id="new-btn" class="ghost primary">New</a></div>
			<a href="<%= user_profile_path(current_user.username) %>" style="float:left;">
				<% if current_user.avatar? %>
					<%= image_tag current_user.avatar.url(:thumb), class: 'avatar' %>
				<% else %>
					<%= image_tag current_user.gravatar, class: 'avatar' %>
				<% end %>
			</a>
			<div id="user-dropdown">
				<ul>
					<li><%= link_to "Profile", user_profile_path(current_user.username) %></li>
					<li><%= link_to "Settings", edit_user_registration_path %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				</ul>
			</div>
		</div>
	</div>
</header>
<% end %>

<div class="padded-top"></div>

app/views/layouts/_messages.html.erb
<% if flash[:error] %>
	<div data-alert id="alert-error" class="alert-box error">
		<%= flash[:error] %>
		<a class="close">x</a>
	</div>
<% end %>

<% if flash[:notice] %>
	<div data-alert id="alert-notice" class="alert-box notice">
		<%= flash[:notice] %>
		<a class="close">x</a>
	</div>
<% end %>

<% if flash[:success] %>
	<div data-alert id="alert-success" class="alert-box success">
		<%= flash[:success] %>
		<a class="close">x</a>
	</div>
<% end %>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title>Oovre Admin Panel</title>
	</head>
	<body>
	
		<%= yield %>
		
	</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title><%= content_for?(:title) ? yield(:title) : "Oovre" %></title>
		<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,100italic,300italic,400italic' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag "application" %>
		<%= content_for?(:meta) ? yield(:meta) : nil %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		
		<%= render 'layouts/header' %>
		<%= render 'layouts/messages' %>
		
		<%= yield %>

		<%= render 'layouts/footer' %>
		
		<% if user_signed_in? %>
			<%= render 'articles/new' %>
		<% end %>
		<%= javascript_include_tag "app" %>

	</body>

</html>